[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "flask-assets>=2.1.0",
    "gunicorn>=23.0.0",
    "libsass>=0.23.0",
    "python-dotenv>=1.0.1",
]
